{% set version = "4.0.0" %}

package:
  name: croniter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/croniter/croniter-{{ version }}.tar.gz
  sha256: 3df735b70d005b68414d80728987ecba4d71054a1bb1b011f6d475bdefdbeddd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7
    - python-dateutil
    - pytz >2021.1

test:
  source_files:
    - src/croniter/tests
  requires:
    - coverage >=4.2
    - pip
    - pytest >=3.0.3
    - pytest-cov
    - tzlocal
  imports:
    - croniter
  commands:
    - pip check

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: croniter provides iteration for datetime object with cron like format
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
