{% set version = "5.0.1" %}

package:
  name: croniter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/croniter/croniter-{{ version }}.tar.gz
  sha256: 7d9b1ef25b10eece48fdf29d8ac52f9b6252abff983ac614ade4f3276294019e

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - python-dateutil
    - pytz >2021.1

test:
  source_files:
    - src/croniter/tests
  requires:
    - coverage >=4.2
    - pip
    - pytest >=3.0.3
    - pytest-cov
    - tzlocal
    - python {{ python_min }}
  imports:
    - croniter
  commands:
    - pip check

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: croniter provides iteration for datetime object with cron like format
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
