{% set name = "croniter" %}
{% set version = "0.3.26" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "8dc579890b0bfd10cfc60a2c314de82adf06004bd90d0d7d5b384e19e93a7720" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - python-dateutil

test:
  imports:
    - croniter
    - croniter.tests

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  summary: 'croniter provides iteration for datetime object with cron like format'
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - pmlandwehr
