{% set version = "1.0.13" %}

package:
  name: croniter
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/croniter/croniter-{{ version }}.tar.gz
  sha256: 57f36df4f5a1c31bbf50bbffa3551612c19f6156ab1e88e2e42342ccbb9f9b9a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.6
    - pip
  run:
    - python >=2.6
    - python-dateutil

test:
  source_files:
    - src/croniter/tests
  requires:
    - coverage >=4.2
    - pip
    - pytest >=3.0.3
    - pytest-cov
    - pytz
    - tzlocal
  imports:
    - croniter

about:
  home: https://github.com/kiorky/croniter
  license: MIT
  license_family: MIT
  license_file: docs/LICENSE
  summary: croniter provides iteration for datetime object with cron like format
  dev_url: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - pmlandwehr
    - mariusvniekerk
    - bollwyvl
