# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 6.2.0
  python_check_max: "3.14"

package:
  name: croniter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/croniter/croniter-${{ version }}.tar.gz
  sha256: 89eef610b0356d08ba368463e69b2908d058a762bd78002859521fef76f3361f

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - python-dateutil

tests:
  - python:
      imports: croniter
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - pytest-cov
        - python ${{ python_min }}.*
        - pytz
    script:
      - coverage run --source=croniter --branch -m pytest -vv --tb=long --color=yes --pyargs croniter
      - coverage report --show-missing --skip-covered --fail-under=92

about:
  license: MIT
  license_file: LICENSE
  summary: croniter provides iteration for datetime object with cron like format
  homepage: https://github.com/kiorky/croniter
  repository: https://github.com/kiorky/croniter

extra:
  recipe-maintainers:
    - mariusvniekerk
    - bollwyvl
